---
os: linux
dist: bionic
language: ruby
cache: bundler
rvm:
  - '2.7'

addons:
  apt:
    packages:
      - gcc
      - gfortran

before_install:
  - gem install bundler -v 2.1.2

after_failure:
  - cat /home/travis/build/yoshoku/numo-openblas/vendor/tmp/openblas.log
