name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: [ '2.6', '2.7', '3.0' ]
    steps:
      - uses: actions/checkout@v2
      - name: Install gcc and gfortran
        run: sudo apt-get install -y gcc gfortran
      - name: Set up Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Build and test with Rake
        run: |
          gem install --no-document bundler
          bundle install --jobs 4 --retry 3
          bundle exec rake
